### ISSUE TITLE
Invalid types for PlayOptions, QueueOptions and PlayerOptions

### ISSUE THREAD

**Issue by naseif** [SidisLiveYT/Jericho-Player#51]
As the title says, the library has **invalid** types for some methods and classes. I am using this library in a Typescript project and I have had some issues so far. the PlayOptions, QueueOptions and PlayerOptions are options and therefor they are **_optional!_** however if I initialize an instance of the Player class or if I am trying to create a queue and I want to specify one of the options, I am being forced to specify them all because in the typing file they are declared **_required_** and not optional. See example below

```ts
export type PlayerOptions = {
  readonly extractor: String | 'play-dl' | 'youtube-dl'
  readonly ExtractorStreamOptions?: {
    readonly Limit: Number
    readonly Quality: String | 'high' | 'low' | 'medium'
    readonly Cookies: String | 'YTCookies'
    readonly ByPassYoutubeDLRatelimit: Boolean | void
    readonly YoutubeDLCookiesFilePath: String | '/path/to/Cookie.txt'
    readonly Proxy: String | Array<String> | 'IPAdress:PortNumber'
    readonly UserAgents: Array<String>
  }
  readonly IgnoreError: Boolean
  readonly LeaveOnEmpty: Boolean
  readonly LeaveOnEnd: Boolean
  readonly LeaveOnBotOnly: Boolean
  readonly readonlyLeaveOnEmptyTimedout: Number | 'Time in Seconds'
  readonly LeaveOnEndTimedout: Number | 'Time in Seconds'
  readonly LeaveOnBotOnlyTimedout: Number | 'Time in Seconds'
  readonly NoMemoryLeakMode: Boolean | 'No Memory Leak Mode for Music Player'
}
```

This would not be much of a problem in JavaScript, but its in TypeScript. Not to mention that all the properties of the interfaces are also declared **_readonly_** which usually means these values are not to touch or modify. This also raises confusion. Since Jericho already has default options if non were specified, a fix for this could be making all properties of the mentioned interfaces optional as they should be.

```ts
export type PlayerOptions = {
  extractor?: String | 'play-dl' | 'youtube-dl'
  ExtractorStreamOptions?: {
    Limit?: Number
    Quality?: String | 'high' | 'low' | 'medium'
    Cookies?: String | 'YTCookies'
    ByPassYoutubeDLRatelimit?: Boolean | void
    YoutubeDLCookiesFilePath?: String | '/path/to/Cookie.txt'
    Proxy?: String | Array<String> | 'IPAdress:PortNumber'
    UserAgents?: Array<String>
  }
  IgnoreError?: Boolean
  LeaveOnEmpty?: Boolean
  LeaveOnEnd?: Boolean
  LeaveOnBotOnly?: Boolean
  readonlyLeaveOnEmptyTimedout?: Number | 'Time in Seconds'
  LeaveOnEndTimedout?: Number | 'Time in Seconds'
  LeaveOnBotOnlyTimedout?: Number | 'Time in Seconds'
  NoMemoryLeakMode?: Boolean | 'No Memory Leak Mode for Music Player'
}
```

**Comment by SidisLiveYT** [comment]
> As the title says, the library has **invalid** types for some methods and classes. I am using this library in a Typescript project and I have had some issues so far. the PlayOptions, QueueOptions and PlayerOptions are options and therefor they are **_optional!_** however if I initialize an instance of the Player class or if I am trying to create a queue and I want to specify one of the options, I am being forced to specify them all because in the typing file they are declared **_required_** and not optional. See example below
> 
> ```ts
> export type PlayerOptions = {
>   readonly extractor: String | 'play-dl' | 'youtube-dl'
>   readonly ExtractorStreamOptions?: {
>     readonly Limit: Number
>     readonly Quality: String | 'high' | 'low' | 'medium'
>     readonly Cookies: String | 'YTCookies'
>     readonly ByPassYoutubeDLRatelimit: Boolean | void
>     readonly YoutubeDLCookiesFilePath: String | '/path/to/Cookie.txt'
>     readonly Proxy: String | Array<String> | 'IPAdress:PortNumber'
>     readonly UserAgents: Array<String>
>   }
>   readonly IgnoreError: Boolean
>   readonly LeaveOnEmpty: Boolean
>   readonly LeaveOnEnd: Boolean
>   readonly LeaveOnBotOnly: Boolean
>   readonly readonlyLeaveOnEmptyTimedout: Number | 'Time in Seconds'
>   readonly LeaveOnEndTimedout: Number | 'Time in Seconds'
>   readonly LeaveOnBotOnlyTimedout: Number | 'Time in Seconds'
>   readonly NoMemoryLeakMode: Boolean | 'No Memory Leak Mode for Music Player'
> }
> ```
> 
> This would not be much of a problem in JavaScript, but its in TypeScript. Not to mention that all the properties of the interfaces are also declared **_readonly_** which usually means these values are not to touch or modify. This also raises confusion. Since Jericho already has default options if non were specified, a fix for this could be making all properties of the mentioned interfaces optional as they should be.
> 
> ```ts
> export type PlayerOptions = {
>   extractor?: String | 'play-dl' | 'youtube-dl'
>   ExtractorStreamOptions?: {
>     Limit?: Number
>     Quality?: String | 'high' | 'low' | 'medium'
>     Cookies?: String | 'YTCookies'
>     ByPassYoutubeDLRatelimit?: Boolean | void
>     YoutubeDLCookiesFilePath?: String | '/path/to/Cookie.txt'
>     Proxy?: String | Array<String> | 'IPAdress:PortNumber'
>     UserAgents?: Array<String>
>   }
>   IgnoreError?: Boolean
>   LeaveOnEmpty?: Boolean
>   LeaveOnEnd?: Boolean
>   LeaveOnBotOnly?: Boolean
>   readonlyLeaveOnEmptyTimedout?: Number | 'Time in Seconds'
>   LeaveOnEndTimedout?: Number | 'Time in Seconds'
>   LeaveOnBotOnlyTimedout?: Number | 'Time in Seconds'
>   NoMemoryLeakMode?: Boolean | 'No Memory Leak Mode for Music Player'
> }
> ```

Thanks for informing me . I should have thought about typescript devs . I will be implementing them within 2 - 3 days for sure because I had to apply modified version of extractors
